os: linux
dist: trusty

language: python
python:
  - "2.7"

branches:
  only:
    - master

# Install Java 8 as required by vnu.jar
before_install:
  - sudo apt-get update
  - sudo apt-get install openjdk-8-jre

install:
  - pip install -r dev-requirements.txt

script:
  - html5validator

notifications:
  webhooks: http://build.servo.org:54856/travis
